/apps/opt/application/smartdq/dq_api/onecorp_restart_scripts/onecorpdata/config/config_daily.ini
name:1CorpAdhocRerun, path:/apps/opt/application/smartdq/dq_api/onecorp_restart_scripts/onecorpdata/logs/AdhocRerunRequest_2025-03-12.log
name:MTDT, path:/apps/opt/application/smartdq/dq_api/MLE/logs/metadata/meta_dt_upload_2025-03-12-12-01-08.log
Internal Server Error: /mle/ExecuteHistorySQL/
Traceback (most recent call last):
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 505, in post
    self.logger.error("No file uploaded.")
AttributeError: 'ExecuteHistorySQL' object has no attribute 'logger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 520, in post
    self.logger.error(f"Error processing request: {e}")
AttributeError: 'ExecuteHistorySQL' object has no attribute 'logger'
